/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 27-Nov-2025 16:35:43
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型，二阶节
 * 节数     : 4
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */

//// 替代tmwtypes.h的简化定义
//typedef double real64_T;
//typedef int int32_T; // 根据实际情况调整

/* 
 * Expected path to tmwtypes.h 
 * D:\Tools\MATLAB\R2024b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const double NUM[MWSPT_NSEC][3] = {
  {
     0.9720908360451,                 0,                 0 
  },
  {
                   1,  -0.6229461048516,                 1 
  },
  {
     0.9720908360451,                 0,                 0 
  },
  {
                   1,  -0.6229461048516,                 1 
  },
  {
     0.8655397987678,                 0,                 0 
  },
  {
                   1,  -0.6229461048516,                 1 
  },
  {
     0.8655397987678,                 0,                 0 
  },
  {
                   1,  -0.6229461048516,                 1 
  },
  {
     0.9581124799279,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1 };
const double DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -0.382305867263,   0.9561512896715 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.8207814877725,   0.9593351350107 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -0.765948541043,    0.757442120481 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.3048639304028,   0.7376655182229 
  },
  {
                   1,                 0,                 0 
  }
};
